name: Deploy to GitHub Pages
run-name: ${{ github.actor }} is deploying 🚀
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Type and lint checks
        run: |
          yarn --immutable
          yarn type
          yarn lint
  deploy:
    needs: test
    # Use Windows for @vite-pwa/assets-generator that throw on linux
    # with: /usr/bin/env: ‘node\r’: No such file or directory
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          yarn --immutable
          yarn generate-pwa-assets
          yarn build
        # Client routing workaround for gh-pages
          yarn shx cp dist/index.html dist/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
